name: Playwright Tests

on:
  push:
    branches:  main
  

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'     

      - name: Install dependencies
        run: npm ci

      # Installs Playwright browsers + required OS packages for Ubuntu
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # If your app requires a build (e.g., Next.js, React, Angular), do it here
      # - name: Build app
      #   run: npm run build

      - name: Run Playwright tests
        run: npx playwright test

      # Always upload the HTML report so you can download it from the run
      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
